// src/components/Svelte/Hero.svelte
<script>
  import { onMount } from 'svelte';
  import { fade, fly } from 'svelte/transition';
  import { quintOut } from 'svelte/easing';

  export let headline = "Svelte + Astro = Magic";
  export let description = "Experience the joy of Svelte's reactivity combined with Astro's performance. Write less code, build faster websites.";

  let mounted = false;

  const scrollToDevTools = () => {
    const devtools = document.getElementById('devtools');
    if (devtools) {
      const yOffset = -80; // Offset for fixed headers
      const y = devtools.getBoundingClientRect().top + window.pageYOffset + yOffset;
      window.scrollTo({ top: y, behavior: 'smooth' });
    }
  };

  const features = [
    { title: "Reactive by Default", description: "No more useState or useEffect. Svelte's reactive statements just work.", icon: "⚡" },
    { title: "Zero Runtime", description: "Svelte compiles away, leaving you with vanilla JavaScript that runs at lightning speed.", icon: "🚀" },
    { title: "Truly Magical", description: "Auto-subscriptions, built-in animations, and scoped CSS make development a breeze.", icon: "✨" }
  ];

  const codeExample = `<!-- Simple Svelte Component -->
< script>
  let count = 0;
  $: doubled = count * 2;
</>

<button on:click={() => count++}>
  Count: {count}
</button>

<p>Doubled: {doubled}</p>`;

  const highlights = [
    { title: "Lightning Fast", icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-orange-400"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></svg>' },
    { title: "Zero Runtime", icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-orange-400"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"></path><polyline points="7.5 4.21 12 6.81 16.5 4.21"></polyline><polyline points="7.5 19.79 7.5 14.6 3 12"></polyline><polyline points="21 12 16.5 14.6 16.5 19.79"></polyline><polyline points="3.27 6.96 12 12.01 20.73 6.96"></polyline><line x1="12" y1="22.08" x2="12" y2="12"></line></svg>' },
    { title: "Dark Mode Ready", icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-orange-400"><path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"></path></svg>' }
  ];

  onMount(() => {
    mounted = true;
  });
</script>

<section class="relative min-h-[90vh] flex items-center justify-center text-white px-4 sm:px-8 py-12 mt-16">  
  <div class="max-w-7xl mx-auto">
    <!-- Hero Content -->
    <div class="grid lg:grid-cols-2 gap-12 lg:gap-20 items-center">
      <!-- Left Column -->
      <div class="text-left space-y-8">
        {#if mounted}
          <div in:fly={{ x: -50, duration: 1000, delay: 200, easing: quintOut }} class="space-y-6">
            <h1 class="text-4xl sm:text-5xl lg:text-6xl font-bold leading-tight">
              <span class="bg-gradient-to-r from-orange-400 via-white to-indigo-400 bg-clip-text text-transparent">{headline}</span>
            </h1>
            <p class="text-lg sm:text-xl text-gray-300 leading-relaxed">
              {description}
            </p>
            <button
              on:click={scrollToDevTools}
              class="flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-orange-500 to-orange-600 text-white font-medium rounded-lg hover:shadow-lg hover:shadow-orange-500/20 transition-all duration-300 hover:-translate-y-0.5 group"
            >
              Try Interactive Demo
              <svg 
                xmlns="http://www.w3.org/2000/svg" 
                width="20" 
                height="20" 
                viewBox="0 0 24 24" 
                fill="none" 
                stroke="currentColor" 
                stroke-width="2" 
                stroke-linecap="round" 
                stroke-linejoin="round" 
                class="transform group-hover:translate-y-1 transition-transform duration-200"
              >
                <line x1="12" y1="5" x2="12" y2="19"></line>
                <polyline points="19 12 12 19 5 12"></polyline>
              </svg>
            </button>
          </div>
        {/if}
      </div>

      <!-- Right Column -->
      <div class="relative">
        {#if mounted}
          <!-- Code Preview -->
          <div in:fly={{ x: 50, duration: 1000, delay: 400, easing: quintOut }} class="relative">
            <div class="absolute inset-0 bg-gradient-to-r from-orange-500/20 to-indigo-500/20 blur-2xl rounded-2xl"></div>
            <div class="relative bg-gray-900/80 backdrop-blur-xl rounded-2xl border border-gray-700/50 overflow-hidden">
              <div class="flex items-center gap-2 px-4 py-3 border-b border-gray-700/50 bg-gray-900/50">
                <div class="w-3 h-3 rounded-full bg-red-500"></div>
                <div class="w-3 h-3 rounded-full bg-yellow-500"></div>
                <div class="w-3 h-3 rounded-full bg-green-500"></div>
              </div>
              <pre class="p-6 overflow-x-auto font-mono text-sm">
                <code class="block">{codeExample}</code>
              </pre>
            </div>
          </div>

          <!-- Features Grid -->
          <div class="grid grid-cols-1 sm:grid-cols-3 gap-4 mt-8">
            {#each features as feature, i}
              <div 
                in:fly={{ y: 20, duration: 800, delay: 800 + i * 200, easing: quintOut }}
                class="p-4 rounded-xl bg-gray-800/30 backdrop-blur-md border border-gray-700/50 hover:border-orange-500/50 transition-all duration-300 hover:-translate-y-1 group"
              >
                <div class="text-3xl mb-2 group-hover:scale-110 transition-transform duration-300">{feature.icon}</div>
                <h3 class="text-lg font-semibold mb-1 text-orange-400">{feature.title}</h3>
                <p class="text-sm text-gray-300">{feature.description}</p>
              </div>
            {/each}
          </div>
        {/if}
      </div>
    </div>
  </div>
</section>

<style lang="postcss">
  :global(pre) {
    tab-size: 2;
  }
</style>

// src/components/Solid/Hero.jsx
import { createSignal, createEffect, Show, onMount } from 'solid-js';

const Hero = () => {
  const [activeTab, setActiveTab] = createSignal('solid');
  const [count, setCount] = createSignal(0);
  const [isVisible, setIsVisible] = createSignal(false);

  onMount(() => {
    setTimeout(() => setIsVisible(true), 100);
  });

  const solidCode = `// Solid.js Component
import { createSignal } from 'solid-js';

function Counter() {
  const [count, setCount] = createSignal(0);
  
  return (
    <button 
      class="px-4 py-2 bg-blue-500 text-white"
      onClick={() => setCount(c => c + 1)}
    >
      Clicks: {count()}
    </button>
  );
}`;

  const astroCode = `---
// Astro Page with Solid.js
import Layout from '../layouts/Layout.astro';
import Counter from '../components/Counter';
---

<Layout title="Solid + Astro">
  <main>
    <Counter client:load />
  </main>
</Layout>`;

  return (
    <section class={`relative min-h-screen flex items-center justify-center p-8 transition-all duration-700 transform ${isVisible() ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>
      <div class={`container mx-auto grid md:grid-cols-2 gap-12 items-center transition-all duration-700 delay-200 transform ${isVisible() ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>
        {/* Left Column - Text Content */}
        <div class={`space-y-8 transition-all duration-700 delay-300 transform ${isVisible() ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>
          <div class="space-y-6">
            <h1 class="text-5xl font-bold leading-tight">
              <span class="text-white">Build with</span>{" "}
              <span class="text-transparent bg-clip-text bg-gradient-to-r from-[#4F87C7] to-[#2B5C9B]">
                Solid.js
              </span>{" "}
              <span class="text-white">+</span>{" "}
              <span class="text-transparent bg-clip-text bg-gradient-to-r from-orange-400 to-red-500">
                Astro
              </span>
            </h1>
            <p class="text-xl text-gray-300 leading-relaxed">
              Experience the perfect blend of Solid.js reactivity and Astro's static-first approach.
              Build blazing-fast websites with the finest granular reactivity system.
            </p>
          </div>

          {/* Interactive Demo Button */}
          <div class="bg-gray-800/50 p-6 rounded-xl space-y-4 backdrop-blur-sm relative overflow-hidden group">
            {/* Animated background gradient */}
            <div class="absolute inset-0 bg-gradient-to-r from-[#4F87C7]/10 to-[#2B5C9B]/10 opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
            
            <h3 class="text-lg font-semibold text-gray-300 relative">Experience Solid.js in action:</h3>
            <button
              onClick={() => {
                const editor = document.querySelector('.interactive-playground');
                editor?.scrollIntoView({ behavior: 'smooth', block: 'start' });
              }}
              class="relative w-full px-6 py-4 bg-gradient-to-r from-[#4F87C7] to-[#2B5C9B] text-white rounded-lg 
                     shadow-[0_0_20px_rgba(79,135,199,0.3)] hover:shadow-[0_0_30px_rgba(79,135,199,0.5)]
                     transform hover:scale-[1.02] active:scale-95 transition-all duration-200
                     flex items-center justify-center gap-3 group/btn"
            >
              <span class="text-lg font-semibold">Try the Interactive Code Editor</span>
              <svg 
                xmlns="http://www.w3.org/2000/svg" 
                class="h-5 w-5 transform group-hover/btn:translate-y-1 transition-transform duration-200" 
                fill="none" 
                viewBox="0 0 24 24" 
                stroke="currentColor"
              >
                <path 
                  stroke-linecap="round" 
                  stroke-linejoin="round" 
                  stroke-width="2" 
                  d="M19 14l-7 7m0 0l-7-7m7 7V3"
                />
              </svg>
            </button>
          </div>
        </div>

        {/* Right Column - Code Examples */}
        <div class={`bg-gray-900/70 rounded-2xl backdrop-blur-sm overflow-hidden w-full h-[500px] flex flex-col transition-all duration-700 delay-400 transform ${isVisible() ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>
          {/* Tab Navigation */}
          <div class="flex border-b border-gray-800">
            <button
              class={`px-6 py-3 text-sm font-medium transition-colors duration-200 ${
                activeTab() === 'solid'
                  ? 'text-[#4F87C7] border-b-2 border-[#4F87C7]'
                  : 'text-gray-400 hover:text-gray-300'
              }`}
              onClick={() => setActiveTab('solid')}
            >
              Solid.js
            </button>
            <button
              class={`px-6 py-3 text-sm font-medium transition-colors duration-200 ${
                activeTab() === 'astro'
                  ? 'text-orange-400 border-b-2 border-orange-400'
                  : 'text-gray-400 hover:text-gray-300'
              }`}
              onClick={() => setActiveTab('astro')}
            >
              Astro
            </button>
          </div>

          {/* Code Window */}
          <div class="relative flex-1">
            {/* Window Controls */}
            <div class="absolute top-4 left-4 flex space-x-2 z-10">
              <div class="w-3 h-3 rounded-full bg-red-500"></div>
              <div class="w-3 h-3 rounded-full bg-yellow-500"></div>
              <div class="w-3 h-3 rounded-full bg-green-500"></div>
            </div>

            {/* Code Content */}
            <div class="relative h-full">
              <pre class={`absolute inset-0 p-8 pt-12 font-mono text-sm leading-relaxed transition-opacity duration-300 ${activeTab() === 'solid' ? 'opacity-100' : 'opacity-0'} overflow-auto`}>
                <code class="text-gray-300 whitespace-pre">
                  {solidCode}
                </code>
              </pre>
              <pre class={`absolute inset-0 p-8 pt-12 font-mono text-sm leading-relaxed transition-opacity duration-300 ${activeTab() === 'astro' ? 'opacity-100' : 'opacity-0'} overflow-auto`}>
                <code class="text-gray-300 whitespace-pre">
                  {astroCode}
                </code>
              </pre>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Hero;
