// src/components/Solid/Hero.jsx
import { createSignal, createEffect, Show, onMount } from 'solid-js';

const Hero = () => {
  const [activeTab, setActiveTab] = createSignal('solid');
  const [count, setCount] = createSignal(0);
  const [isVisible, setIsVisible] = createSignal(false);

  onMount(() => {
    setTimeout(() => setIsVisible(true), 100);
  });

  const solidCode = `// Solid.js Component
import { createSignal } from 'solid-js';

function Counter() {
  const [count, setCount] = createSignal(0);
  
  return (
    <button 
      class="px-4 py-2 bg-blue-500 text-white"
      onClick={() => setCount(c => c + 1)}
    >
      Clicks: {count()}
    </button>
  );
}`;

  const astroCode = `---
// Astro Page with Solid.js
import Layout from '../layouts/Layout.astro';
import Counter from '../components/Counter';
---

<Layout title="Solid + Astro">
  <main>
    <Counter client:load />
  </main>
</Layout>`;

  return (
    <section class={`relative min-h-screen flex items-center justify-center p-8 transition-all duration-700 transform ${isVisible() ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>
      <div class={`container mx-auto grid md:grid-cols-2 gap-12 items-center transition-all duration-700 delay-200 transform ${isVisible() ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>
        {/* Left Column - Text Content */}
        <div class={`space-y-8 transition-all duration-700 delay-300 transform ${isVisible() ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>
          <div class="space-y-6">
            <h1 class="text-5xl font-bold leading-tight">
              <span class="text-white">Build with</span>{" "}
              <span class="text-transparent bg-clip-text bg-gradient-to-r from-[#4F87C7] to-[#2B5C9B]">
                Solid.js
              </span>{" "}
              <span class="text-white">+</span>{" "}
              <span class="text-transparent bg-clip-text bg-gradient-to-r from-orange-400 to-red-500">
                Astro
              </span>
            </h1>
            <p class="text-xl text-gray-300 leading-relaxed">
              Experience the perfect blend of Solid.js reactivity and Astro's static-first approach.
              Build blazing-fast websites with the finest granular reactivity system.
            </p>
          </div>

          {/* Interactive Demo Button */}
          <div class="bg-gray-800/50 p-6 rounded-xl space-y-4 backdrop-blur-sm relative overflow-hidden group">
            {/* Animated background gradient */}
            <div class="absolute inset-0 bg-gradient-to-r from-[#4F87C7]/10 to-[#2B5C9B]/10 opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
            
            <h3 class="text-lg font-semibold text-gray-300 relative">Experience Solid.js in action:</h3>
            <button
              onClick={() => {
                const editor = document.querySelector('.interactive-playground');
                editor?.scrollIntoView({ behavior: 'smooth', block: 'start' });
              }}
              class="relative w-full px-6 py-4 bg-gradient-to-r from-[#4F87C7] to-[#2B5C9B] text-white rounded-lg 
                     shadow-[0_0_20px_rgba(79,135,199,0.3)] hover:shadow-[0_0_30px_rgba(79,135,199,0.5)]
                     transform hover:scale-[1.02] active:scale-95 transition-all duration-200
                     flex items-center justify-center gap-3 group/btn"
            >
              <span class="text-lg font-semibold">Try the Interactive Code Editor</span>
              <svg 
                xmlns="http://www.w3.org/2000/svg" 
                class="h-5 w-5 transform group-hover/btn:translate-y-1 transition-transform duration-200" 
                fill="none" 
                viewBox="0 0 24 24" 
                stroke="currentColor"
              >
                <path 
                  stroke-linecap="round" 
                  stroke-linejoin="round" 
                  stroke-width="2" 
                  d="M19 14l-7 7m0 0l-7-7m7 7V3"
                />
              </svg>
            </button>
          </div>
        </div>

        {/* Right Column - Code Examples */}
        <div class={`bg-gray-900/70 rounded-2xl backdrop-blur-sm overflow-hidden w-full h-[500px] flex flex-col transition-all duration-700 delay-400 transform ${isVisible() ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>
          {/* Tab Navigation */}
          <div class="flex border-b border-gray-800">
            <button
              class={`px-6 py-3 text-sm font-medium transition-colors duration-200 ${
                activeTab() === 'solid'
                  ? 'text-[#4F87C7] border-b-2 border-[#4F87C7]'
                  : 'text-gray-400 hover:text-gray-300'
              }`}
              onClick={() => setActiveTab('solid')}
            >
              Solid.js
            </button>
            <button
              class={`px-6 py-3 text-sm font-medium transition-colors duration-200 ${
                activeTab() === 'astro'
                  ? 'text-orange-400 border-b-2 border-orange-400'
                  : 'text-gray-400 hover:text-gray-300'
              }`}
              onClick={() => setActiveTab('astro')}
            >
              Astro
            </button>
          </div>

          {/* Code Window */}
          <div class="relative flex-1">
            {/* Window Controls */}
            <div class="absolute top-4 left-4 flex space-x-2 z-10">
              <div class="w-3 h-3 rounded-full bg-red-500"></div>
              <div class="w-3 h-3 rounded-full bg-yellow-500"></div>
              <div class="w-3 h-3 rounded-full bg-green-500"></div>
            </div>

            {/* Code Content */}
            <div class="relative h-full">
              <pre class={`absolute inset-0 p-8 pt-12 font-mono text-sm leading-relaxed transition-opacity duration-300 ${activeTab() === 'solid' ? 'opacity-100' : 'opacity-0'} overflow-auto`}>
                <code class="text-gray-300 whitespace-pre">
                  {solidCode}
                </code>
              </pre>
              <pre class={`absolute inset-0 p-8 pt-12 font-mono text-sm leading-relaxed transition-opacity duration-300 ${activeTab() === 'astro' ? 'opacity-100' : 'opacity-0'} overflow-auto`}>
                <code class="text-gray-300 whitespace-pre">
                  {astroCode}
                </code>
              </pre>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Hero;

// src/components/React/Hero.tsx
import React from 'react';
import { motion, LazyMotion, domAnimation } from 'framer-motion';

const LivePreview: React.FC = () => {
  const [color, setColor] = React.useState('#3B82F6');
  
  return (
    <LazyMotion features={domAnimation}>
      <motion.div
        className="relative"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <div className="bg-gray-900 rounded-2xl border border-gray-800 flex flex-col">
          <div className="flex items-center justify-between p-2 border-b border-gray-800">
            <div className="flex items-center gap-2">
              <div className="w-3 h-3 rounded-full bg-red-500"></div>
              <div className="w-3 h-3 rounded-full bg-yellow-500"></div>
              <div className="w-3 h-3 rounded-full bg-green-500"></div>
            </div>
            <div className="text-sm text-gray-400">Live Preview</div>
          </div>
          
          <div className="p-1 m-7">
            <div className="space-y-3">
              <div className="text-center space-y-2">
                <p className="text-gray-300 font-medium">Try it yourself!</p>
                <p className="text-sm text-gray-400">Click the input below to choose a color</p>
              </div>
              <input 
                type="color" 
                value={color}
                onChange={(e) => setColor(e.target.value)}
                className="w-full h-12 rounded-lg cursor-pointer bg-transparent hover:scale-[1.02] transition-transform"
              />
              <div className="text-center">
                <p className="text-sm text-gray-400">Selected color: <span className="font-mono text-gray-300">{color}</span></p>
              </div>
            </div>
          </div>
        </div>
      </motion.div>
    </LazyMotion>
  );
};

interface CodeCardProps {
  title: string;
  code: string;
}

const CodeCard: React.FC<CodeCardProps> = ({ title, code }) => (
  <LazyMotion features={domAnimation}>
    <motion.div
      className="relative"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
    >
      <div className="bg-gray-900 p-6 rounded-2xl border border-gray-800">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <div className="w-3 h-3 rounded-full bg-red-500" />
            <div className="w-3 h-3 rounded-full bg-yellow-500" />
            <div className="w-3 h-3 rounded-full bg-green-500" />
          </div>
          <div className="text-sm text-gray-400">{title}</div>
        </div>
        <pre className="overflow-x-auto">
          <code className="block text-sm text-gray-300">{code}</code>
        </pre>
      </div>
    </motion.div>
  </LazyMotion>
);

const Hero: React.FC = () => {
  const reactCode = 
  ` 
// Color Picker Component
import { useState } from 'react';

const ColorPicker = () => {
  const [color, setColor] = useState('#3B82F6');
  
  return (
    <div className="space-y-4">
      <input 
        type="color" 
        value={color}
        onChange={(e) => setColor(e.target.value)}
      />
      <div 
        style={{ backgroundColor: color }}
        className="w-full h-20 rounded-lg shadow-lg"
      />
    </div>
  );
};

export default ColorPicker;`;

  const astroCode = `---
// pages/index.astro
import ColorPicker from '../components/ColorPicker';
---

<div class="my-component">
  <h2>Interactive Color Picker</h2>
  <ColorPicker client:load />
</div>`;

  const scrollToChat = () => {
    const chatSection = document.getElementById('chat-section');
    if (chatSection) {
      chatSection.scrollIntoView({ behavior: 'smooth' });
    }
  };

  return (
    <section className="min-h-[80vh] relative flex items-center justify-center py-20 mt-20">      
      <div className="container mx-auto px-4 relative z-10">
        <div className="max-w-4xl mx-auto text-center mb-12">
          <LazyMotion features={domAnimation}>
            <motion.h1 
              className="text-5xl md:text-6xl font-bold text-gray-300 mb-6"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              React + Astro
            </motion.h1>
          </LazyMotion>
          <LazyMotion features={domAnimation}>
            <motion.p 
              className="text-xl text-gray-300 mb-12"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.2 }}
            >
              Build dynamic, interactive components with the power of React in your Astro pages.
            </motion.p>
          </LazyMotion>
          <LazyMotion features={domAnimation}>
            <motion.button
              onClick={scrollToChat}
              className="group px-6 py-3 bg-gradient-to-r from-purple-600 to-indigo-700 text-white rounded-xl font-medium hover:from-purple-700 hover:to-indigo-800 transition-all duration-200 shadow-lg hover:shadow-xl flex items-center gap-2 mx-auto"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.4 }}
              whileHover={{ y: 2 }}
            >
              Chat with Me
              <svg 
                xmlns="http://www.w3.org/2000/svg" 
                className="h-5 w-5 transform group-hover:translate-y-1 transition-transform duration-200" 
                fill="none" 
                viewBox="0 0 24 24" 
                stroke="currentColor"
              >
                <path 
                  strokeLinecap="round" 
                  strokeLinejoin="round" 
                  strokeWidth={2} 
                  d="M19 14l-7 7m0 0l-7-7m7 7V3" 
                />
              </svg>
            </motion.button>
          </LazyMotion>
        </div>

        <div className="grid md:grid-cols-2 gap-8 max-w-5xl mx-auto">
          <CodeCard title="ColorPicker.tsx" code={reactCode} />
          <div className="space-y-8">
            <CodeCard title="index.astro" code={astroCode} />
            <LivePreview />
          </div>
        </div>
      </div>
    </section>
  );
};

export default Hero;
